apiVersion: v1
kind: Pod
metadata:
  name: avr8-mplabx
spec:
  containers:
    - name: avr8-mplabx
      image: artifacts.microchip.com:7999/microchip/citd/bundles/avr8-mplabx:latest
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 0.25
          memory: 500Mi
        limits:
          cpu: 0.5
          memory: 750Mi